name: deploy

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up terraform
        uses: hashicorp/setup-terraform@v2

      - name: Deploy
        env: 
          COCKROACH_API_KEY: ${{ secrets.COCKROACH_API_KEY }} 
        run: |
          terraform apply \
            -var='cluster_name=${{ secrets.COCKROACH_CLUSTER_NAME }}' \
            -var='sql_user_name=${{ secrets.COCKROACH_SQL_USER_NAME }}' \
            -var='sql_user_password=${{ secrets.COCKROACH_SQL_USER_PASSWORD }}'
